// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgl3l9qYiwKksiFBcVNa601xjLPpSZT8o',
    appId: '1:190825878039:web:b0edadbf2634aac6e38252',
    messagingSenderId: '190825878039',
    projectId: 'test-project-modul3',
    authDomain: 'test-project-modul3.firebaseapp.com',
    storageBucket: 'test-project-modul3.appspot.com',
    measurementId: 'G-CRFFCM152D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWXuPaB3_T-TsDPMuJZV93LN6LvOMOAh0',
    appId: '1:190825878039:android:33c722546c2bed57e38252',
    messagingSenderId: '190825878039',
    projectId: 'test-project-modul3',
    storageBucket: 'test-project-modul3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXUJFvyE4DiwcSBBo4mgvPMqQ-jAgY0wc',
    appId: '1:190825878039:ios:2907870a46e05c4de38252',
    messagingSenderId: '190825878039',
    projectId: 'test-project-modul3',
    storageBucket: 'test-project-modul3.appspot.com',
    iosBundleId: 'com.example.codelabmodul3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXUJFvyE4DiwcSBBo4mgvPMqQ-jAgY0wc',
    appId: '1:190825878039:ios:2907870a46e05c4de38252',
    messagingSenderId: '190825878039',
    projectId: 'test-project-modul3',
    storageBucket: 'test-project-modul3.appspot.com',
    iosBundleId: 'com.example.codelabmodul3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgl3l9qYiwKksiFBcVNa601xjLPpSZT8o',
    appId: '1:190825878039:web:28cea342cab19aa4e38252',
    messagingSenderId: '190825878039',
    projectId: 'test-project-modul3',
    authDomain: 'test-project-modul3.firebaseapp.com',
    storageBucket: 'test-project-modul3.appspot.com',
    measurementId: 'G-YV27C0EQ69',
  );

}